spring:
  datasource:
    url: jdbc:h2:mem:hexagonal
    username: adm
    password: adm
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

h2:
  console:
    enabled: true
    path: /h2-console